$$\begin{cases} 
4x_1-3x_2+x_3=-10, \\ 2x_1+x_2+3x_3=0, \\ -x_1+2x_2-5x_3=17, \end{cases}\tag{1}$$

# Solving Persamaan diata

In [2]:
import numpy as np

### Bikin Representasi persamaan diatas

In [3]:
A = np.array([
        [4, -3, 1],
        [2, 1, 3],
        [-1, 2, -5]
    ], dtype=np.dtype(float))

b = np.array([-10, 0, 17], dtype=np.dtype(float))

print("Matrix A:")
print(A)
print("\nArray b:")
print(b)

Matrix A:
[[ 4. -3.  1.]
 [ 2.  1.  3.]
 [-1.  2. -5.]]

Array b:
[-10.   0.  17.]


### Lihat dimensi persamaan

In [4]:
print(f"Shape of A: {np.shape(A)}")
print(f"Shape of b: {np.shape(b)}")

Shape of A: (3, 3)
Shape of b: (3,)


### Solusi persamaan diatas

In [5]:
x = np.linalg.solve(A, b)

print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


### Sekarang Kita terapkan pada kasus nyata

#### Kasus Nyata: Pembagian Biaya

#### Situasi
Ada tiga orang (A, B, dan C) yang berbagi biaya sewa rumah dan pengeluaran lainnya:

- **Total biaya sewa rumah**: Rp 4.000.000
- **A menghabiskan**: Rp 1.000.000 untuk makanan
- **B menghabiskan**: Rp 600.000 untuk listrik dan air
- **C menghabiskan**: Rp 1.200.000 untuk barang-barang rumah tangga

#### Model Persamaan
Dari situasi ini, kita menyusun sistem persamaan sebagai berikut:

1. \( x_1 + x_2 + x_3 = 4.000.000 \)  (Total biaya)
2. \( x_1 - 1.000.000 = 0 \)  (A mengembalikan biaya makanan)
3. \( x_2 - 600.000 = 0 \)  (B mengembalikan biaya listrik dan air)
4. \( x_3 - 1.200.000 = 0 \)  (C mengembalikan biaya barang)

#### Sistem Persamaan dalam Bentuk Matriks
Matriks koefisien \( A \) dan array \( b \) dapat ditulis sebagai:

#### Matriks Koefisien \( A \)

\[
A = 
\begin{bmatrix}
1 & 1 & 1 \\
1 & 0 & 0 \\
0 & 1 & 0 \\
0 & 0 & 1
\end{bmatrix}
\]

#### Array \( b \)

\[
b = 
\begin{bmatrix}
4.000.000 \\
1.000.000 \\
600.000 \\
1.200.000
\end{bmatrix}
\]

#### Langkah-langkah Perhitungan

Dari persamaan kedua, kita udah tahu:

\[ x_1 = 1.000.000 \]

Dari persamaan ketiga, kita juga tahu:

\[ x_2 = 600.000 \]

Dan dari persamaan keempat, kita dapat:

\[ x_3 = 1.200.000 \]

Sekarang, kita coba substitusi nilai \( x_1 \), \( x_2 \), dan \( x_3 \) ke dalam persamaan pertama buat cek apakah semua sesuai:

#### Substitusi

\[
x_1 + x_2 + x_3 = 4.000.000
\]

Coba substitusi:

\[
1.000.000 + 600.000 + 1.200.000 = 4.000.000
\]

#### Hitung

\[
1.000.000 + 600.000 = 1.600.000
\]

\[
1.600.000 + 1.200.000 = 2.800.000
\]

Uh-oh, ini nggak nyampe total Rp 4.000.000!

#### Menyesuaikan Kontribusi

Karena nilai \( x_1 \), \( x_2 \), dan \( x_3 \) nggak sesuai, kita perlu cari kontribusi yang lebih pas.

Kita tahu total biaya yang dibayar A, B, dan C itu Rp 4.000.000. Mari kita coba cara lain!

#### Menyusun Kontribusi

Dari total, kita bisa hitung kontribusi yang beneran:

#### Total kontribusi:

\[
x_1 = 1.000.000
\]

\[
x_2 = 600.000
\]

\[
x_3 = 4.000.000 - (x_1 + x_2)
\]

#### Substitusi:

\[
x_3 = 4.000.000 - (1.000.000 + 600.000) = 4.000.000 - 1.600.000 = 2.400.000
\]

#### Hasil Akhir

Jadi, kontribusi yang harus dibayar:

- \( x_1 \) (A): Rp 1.000.000
- \( x_2 \) (B): Rp 600.000
- \( x_3 \) (C): Rp 2.400.000


#### Mulai Coding

In [23]:
# Matriks koefisien
cost_distribution_matrix = np.array([
    [1, 1, 1],  # Total kontribusi dari A, B, dan C
    [1, 0, 0],  # Kontribusi A untuk makanan
    [0, 1, 0],  # Kontribusi B untuk listrik dan air
], dtype=float)

print(cost_distribution_matrix)


[[1. 1. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [20]:
# Array dari total biaya
total_costs = np.array([4_000_000, 1_000_000, 600_000], dtype=float)

print(total_costs)

[4000000. 1000000.  600000.]


In [21]:
# Menyelesaikan sistem persamaan
contributions = np.linalg.solve(cost_distribution_matrix, total_costs)

print(contributions)

[1000000.  600000. 2400000.]


In [22]:
# Menampilkan hasil dengan pemisah ribuan
amount_paid_by_A = contributions[0]
amount_paid_by_B = contributions[1]
amount_paid_by_C = total_costs[0] - amount_paid_by_A - amount_paid_by_B

print(amount_paid_by_C)

2400000.0


In [19]:
# Menggunakan format string untuk menampilkan dengan pemisah ribuan
print(f"Jumlah yang harus dibayar oleh A: {amount_paid_by_A:,.2f}")
print(f"Jumlah yang harus dibayar oleh B: {amount_paid_by_B:,.2f}")
print(f"Jumlah yang harus dibayar oleh C: {amount_paid_by_C:,.2f}")

Jumlah yang harus dibayar oleh A: 1,000,000.00
Jumlah yang harus dibayar oleh B: 600,000.00
Jumlah yang harus dibayar oleh C: 2,400,000.00
